# Source endeavor-zsh-configuration
if [[ -e /usr/share/zsh/endeavor-zsh-config ]]; then
  source /usr/share/zsh/endesvor-zsh-config
fi

source ~/.local/share/omakub/defaults/zsh/rc

# Editor used by CLI
export EDITOR="nvim"
export SUDO_EDITOR="$EDITOR"
